//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wResAPI_d3xd
{
    using System;
    using System.Collections.Generic;
    
    public partial class otrmoney
    {
        public int vdecov { get; set; }
        public Nullable<double> vcambioa1 { get; set; }
        public Nullable<double> vcambiob1 { get; set; }
        public string vnomb1 { get; set; }
        public Nullable<int> otipo1 { get; set; }
        public Nullable<double> vcambioa2 { get; set; }
        public Nullable<double> vcambiob2 { get; set; }
        public string vnomb2 { get; set; }
        public Nullable<int> otipo2 { get; set; }
        public Nullable<double> vcambioa3 { get; set; }
        public Nullable<double> vcambiob3 { get; set; }
        public string vnomb3 { get; set; }
        public Nullable<int> otipo3 { get; set; }
        public Nullable<double> vcambioa4 { get; set; }
        public Nullable<double> vcambiob4 { get; set; }
        public string vnomb4 { get; set; }
        public Nullable<int> otipo4 { get; set; }
        public Nullable<double> vcambioa5 { get; set; }
        public Nullable<double> vcambiob5 { get; set; }
        public string vnomb5 { get; set; }
        public Nullable<int> otipo5 { get; set; }
    }
}
