//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wResAPI_d3xd
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public string pcode { get; set; }
        public string preferencia { get; set; }
        public string pdescribe { get; set; }
        public Nullable<int> pdepaid { get; set; }
        public string pdepartamento { get; set; }
        public Nullable<int> plinid { get; set; }
        public string psublinea { get; set; }
        public Nullable<int> plinida { get; set; }
        public string psublineaa { get; set; }
        public Nullable<int> pmarid { get; set; }
        public string pmarca { get; set; }
        public Nullable<int> pproid { get; set; }
        public string pproveedor { get; set; }
        public string pgarantia { get; set; }
        public string pextras { get; set; }
        public Nullable<double> pcosto { get; set; }
        public Nullable<double> pcostoreal { get; set; }
        public Nullable<double> pgastos { get; set; }
        public Nullable<double> pdesc1 { get; set; }
        public Nullable<double> pventa1 { get; set; }
        public Nullable<double> pporc1 { get; set; }
        public Nullable<double> pventa2 { get; set; }
        public Nullable<double> pporc2 { get; set; }
        public Nullable<double> pventa3 { get; set; }
        public Nullable<double> pporc3 { get; set; }
        public Nullable<double> pventa4 { get; set; }
        public Nullable<double> pporc4 { get; set; }
        public Nullable<double> pventa5 { get; set; }
        public Nullable<double> pporc5 { get; set; }
        public Nullable<double> pempaque { get; set; }
        public Nullable<int> pmaxp2 { get; set; }
        public Nullable<int> pmaxp3 { get; set; }
        public string pmedida { get; set; }
        public string pmedempaque { get; set; }
        public Nullable<int> piva { get; set; }
        public Nullable<int> pserialchk { get; set; }
        public Nullable<int> pden { get; set; }
        public Nullable<double> pexiste { get; set; }
        public Nullable<double> pdeposito1 { get; set; }
        public Nullable<double> pdeposito2 { get; set; }
        public Nullable<double> pdeposito3 { get; set; }
        public Nullable<double> pdeposito4 { get; set; }
        public Nullable<int> pdeposito5 { get; set; }
        public Nullable<int> pdeposito6 { get; set; }
        public Nullable<int> pdeposito7 { get; set; }
        public Nullable<int> pdeposito8 { get; set; }
        public Nullable<int> pdeposito9 { get; set; }
        public Nullable<int> pdeposito10 { get; set; }
        public string pubicaplace { get; set; }
        public Nullable<double> pcomprometido { get; set; }
        public Nullable<double> papartado { get; set; }
        public Nullable<double> pproduce { get; set; }
        public Nullable<double> pcostoxuniini { get; set; }
        public Nullable<double> pinventarioinicial { get; set; }
        public Nullable<double> pcostoinventi { get; set; }
        public Nullable<double> pentradasx { get; set; }
        public Nullable<double> ptotalentradas { get; set; }
        public Nullable<double> psalidasx { get; set; }
        public Nullable<double> ptotalsalidas { get; set; }
        public Nullable<double> pajustadox { get; set; }
        public Nullable<double> ptotalajustado { get; set; }
        public Nullable<double> ptrasladoenviado { get; set; }
        public Nullable<double> ptrasladorecibido { get; set; }
        public Nullable<double> pproducido { get; set; }
        public Nullable<double> ptotalproducido { get; set; }
        public Nullable<double> pinproduce { get; set; }
        public Nullable<double> ptotinproduce { get; set; }
        public Nullable<double> psucursal { get; set; }
        public Nullable<double> pagotado { get; set; }
        public string pfechaV { get; set; }
        public Nullable<double> pcostosalen { get; set; }
        public Nullable<double> phoy { get; set; }
        public Nullable<double> ptotalhoy { get; set; }
        public Nullable<double> pehoy { get; set; }
        public Nullable<double> petotalhoy { get; set; }
        public string pobservacion { get; set; }
        public Nullable<int> prestinge { get; set; }
        public Nullable<int> prestinmax { get; set; }
        public Nullable<double> pdescuenta { get; set; }
        public Nullable<double> pcomision { get; set; }
        public Nullable<double> pchistoric { get; set; }
        public Nullable<int> ploteis { get; set; }
        public Nullable<int> ptallais { get; set; }
        public Nullable<int> pcoloris { get; set; }
        public string pintercode { get; set; }
        public string pdatevoid { get; set; }
        public Nullable<int> pmoneydif { get; set; }
        public Nullable<int> pcahonta { get; set; }
        public Nullable<double> plitros { get; set; }
        public Nullable<int> pgrados { get; set; }
        public string pespecie { get; set; }
        public Nullable<int> plock { get; set; }
    }
}
